### ISSUE TITLE
WebVTT.read(file) raises NoMethodError: undefined method `exists?' for File:Class in Ruby 3.2.0

### ISSUE THREAD

**Issue by synthead** [opencoconut/webvtt-ruby#19]
File.exists? is deprecated in Ruby 3.2.0 , so these lines don't work in Ruby 3.2.0 anymore:

https://github.com/opencoconut/webvtt-ruby/blob/5cad6b7710f28c2880a8b74cfba25a35f0ce65fc/lib/webvtt/parser.rb#L12

https://github.com/opencoconut/webvtt-ruby/blob/5cad6b7710f28c2880a8b74cfba25a35f0ce65fc/lib/webvtt/parser.rb#L87

...and this test is broken:

https://github.com/opencoconut/webvtt-ruby/blob/5cad6b7710f28c2880a8b74cfba25a35f0ce65fc/tests/segmenter.rb#L46
